dtd = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" [ ' \
    '<!ENTITY nbsp      \' \'> ' \
    '<!ENTITY ensp      \' \'> ' \
    '<!ENTITY frasl     \' \'> ' \
    '<!ENTITY quot		\' \'> ' \
    '<!ENTITY apos		\' \'> ' \
    '<!ENTITY amp		\' \'> ' \
    '<!ENTITY lt		\' \'> ' \
    '<!ENTITY gt		\' \'> ' \
    '<!ENTITY iexcl		\' \'> ' \
    '<!ENTITY cent		\' \'> ' \
    '<!ENTITY pound		\' \'> ' \
    '<!ENTITY curren	\' \'> ' \
    '<!ENTITY yen		\' \'> ' \
    '<!ENTITY brvbar	\' \'> ' \
    '<!ENTITY sect		\' \'> ' \
    '<!ENTITY uml		\' \'> ' \
    '<!ENTITY copy		\' \'> ' \
    '<!ENTITY ordf		\' \'> ' \
    '<!ENTITY laquo		\' \'> ' \
    '<!ENTITY not		\' \'> ' \
    '<!ENTITY reg		\' \'> ' \
    '<!ENTITY deg		\' \'> ' \
    '<!ENTITY plusmn	\' \'> ' \
    '<!ENTITY sup2		\' \'> ' \
    '<!ENTITY sup3		\' \'> ' \
    '<!ENTITY acute		\' \'> ' \
    '<!ENTITY micro		\' \'> ' \
    '<!ENTITY para		\' \'> ' \
    '<!ENTITY middot	\' \'> ' \
    '<!ENTITY sup1		\' \'> ' \
    '<!ENTITY ordm		\' \'> ' \
    '<!ENTITY raquo		\' \'> ' \
    '<!ENTITY frac14	\' \'> ' \
    '<!ENTITY frac12	\' \'> ' \
    '<!ENTITY frac34	\' \'> ' \
    '<!ENTITY iquest	\' \'> ' \
    '<!ENTITY times		\' \'> ' \
    '<!ENTITY divide	\' \'> ' \
    '<!ENTITY Agrave    \' \'> ' \
    '<!ENTITY Aacute	\' \'> ' \
    '<!ENTITY Acirc		\' \'> ' \
    '<!ENTITY Atilde	\' \'> ' \
    '<!ENTITY Auml		\' \'> ' \
    '<!ENTITY Aring		\' \'> ' \
    '<!ENTITY AElig		\' \'> ' \
    '<!ENTITY Ccedil	\' \'> ' \
    '<!ENTITY Egrave	\' \'> ' \
    '<!ENTITY Eacute	\' \'> ' \
    '<!ENTITY Ecirc		\' \'> ' \
    '<!ENTITY Euml		\' \'> ' \
    '<!ENTITY Igrave	\' \'> ' \
    '<!ENTITY Iacute	\' \'> ' \
    '<!ENTITY Icirc		\' \'> ' \
    '<!ENTITY Iuml		\' \'> ' \
    '<!ENTITY ETH		\' \'> ' \
    '<!ENTITY Ntilde	\' \'> ' \
    '<!ENTITY Ograve	\' \'> ' \
    '<!ENTITY Oacute	\' \'> ' \
    '<!ENTITY Ocirc		\' \'> ' \
    '<!ENTITY Otilde	\' \'> ' \
    '<!ENTITY Ouml		\' \'> ' \
    '<!ENTITY Oslash	\' \'> ' \
    '<!ENTITY Ugrave	\' \'> ' \
    '<!ENTITY Uacute	\' \'> ' \
    '<!ENTITY Ucirc		\' \'> ' \
    '<!ENTITY Uuml		\' \'> ' \
    '<!ENTITY Yacute	\' \'> ' \
    '<!ENTITY THORN		\' \'> ' \
    '<!ENTITY szlig		\' \'> ' \
    '<!ENTITY agrave	\' \'> ' \
    '<!ENTITY aacute	\' \'> ' \
    '<!ENTITY acirc		\' \'> ' \
    '<!ENTITY atilde	\' \'> ' \
    '<!ENTITY auml		\' \'> ' \
    '<!ENTITY aring		\' \'> ' \
    '<!ENTITY aelig		\' \'> ' \
    '<!ENTITY ccedil	\' \'> ' \
    '<!ENTITY egrave	\' \'> ' \
    '<!ENTITY eacute	\' \'> ' \
    '<!ENTITY ecirc		\' \'> ' \
    '<!ENTITY euml		\' \'> ' \
    '<!ENTITY igrave	\' \'> ' \
    '<!ENTITY iacute	\' \'> ' \
    '<!ENTITY icirc		\' \'> ' \
    '<!ENTITY iuml		\' \'> ' \
    '<!ENTITY eth		\' \'> ' \
    '<!ENTITY ntilde	\' \'> ' \
    '<!ENTITY ograve	\' \'> ' \
    '<!ENTITY oacute	\' \'> ' \
    '<!ENTITY ocirc		\' \'> ' \
    '<!ENTITY otilde	\' \'> ' \
    '<!ENTITY ouml		\' \'> ' \
    '<!ENTITY oslash	\' \'> ' \
    '<!ENTITY ugrave	\' \'> ' \
    '<!ENTITY uacute	\' \'> ' \
    '<!ENTITY ucirc		\' \'> ' \
    '<!ENTITY uuml		\' \'> ' \
    '<!ENTITY yacute	\' \'> ' \
    '<!ENTITY yuml		\' \'> ' \
    '<!ENTITY forall	\' \'> ' \
    '<!ENTITY part		\' \'> ' \
    '<!ENTITY exist		\' \'> ' \
    '<!ENTITY empty		\' \'> ' \
    '<!ENTITY nabla		\' \'> ' \
    '<!ENTITY isin		\' \'> ' \
    '<!ENTITY notin		\' \'> ' \
    '<!ENTITY ni		\' \'> ' \
    '<!ENTITY sum		\' \'> ' \
    '<!ENTITY minus		\' \'> ' \
    '<!ENTITY lowast	\' \'> ' \
    '<!ENTITY radic		\' \'> ' \
    '<!ENTITY prop		\' \'> ' \
    '<!ENTITY infin		\' \'> ' \
    '<!ENTITY ang		\' \'> ' \
    '<!ENTITY and		\' \'> ' \
    '<!ENTITY or		\' \'> ' \
    '<!ENTITY cap		\' \'> ' \
    '<!ENTITY cup		\' \'> ' \
    '<!ENTITY int		\' \'> ' \
    '<!ENTITY sim		\' \'> ' \
    '<!ENTITY cong		\' \'> ' \
    '<!ENTITY asymp		\' \'> ' \
    '<!ENTITY ne		\' \'> ' \
    '<!ENTITY equiv		\' \'> ' \
    '<!ENTITY le		\' \'> ' \
    '<!ENTITY ge		\' \'> ' \
    '<!ENTITY perp		\' \'> ' \
    '<!ENTITY Alpha		\' \'> ' \
    '<!ENTITY Beta		\' \'> ' \
    '<!ENTITY Gamma		\' \'> ' \
    '<!ENTITY Delta		\' \'> ' \
    '<!ENTITY Epsilon	\' \'> ' \
    '<!ENTITY Zeta		\' \'> ' \
    '<!ENTITY Eta		\' \'> ' \
    '<!ENTITY Theta		\' \'> ' \
    '<!ENTITY Iota		\' \'> ' \
    '<!ENTITY Kappa		\' \'> ' \
    '<!ENTITY Lambda	\' \'> ' \
    '<!ENTITY Mu		\' \'> ' \
    '<!ENTITY Nu		\' \'> ' \
    '<!ENTITY Xi		\' \'> ' \
    '<!ENTITY Omicron	\' \'> ' \
    '<!ENTITY Pi		\' \'> ' \
    '<!ENTITY Rho		\' \'> ' \
    '<!ENTITY Sigma		\' \'> ' \
    '<!ENTITY Tau		\' \'> ' \
    '<!ENTITY Upsilon	\' \'> ' \
    '<!ENTITY Phi		\' \'> ' \
    '<!ENTITY Chi		\' \'> ' \
    '<!ENTITY Psi		\' \'> ' \
    '<!ENTITY Omega		\' \'> ' \
    '<!ENTITY alpha		\' \'> ' \
    '<!ENTITY beta		\' \'> ' \
    '<!ENTITY gamma		\' \'> ' \
    '<!ENTITY delta		\' \'> ' \
    '<!ENTITY epsilon	\' \'> ' \
    '<!ENTITY zeta		\' \'> ' \
    '<!ENTITY eta		\' \'> ' \
    '<!ENTITY theta		\' \'> ' \
    '<!ENTITY iota		\' \'> ' \
    '<!ENTITY kappa		\' \'> ' \
    '<!ENTITY lambda	\' \'> ' \
    '<!ENTITY mu		\' \'> ' \
    '<!ENTITY nu		\' \'> ' \
    '<!ENTITY xi		\' \'> ' \
    '<!ENTITY omicron	\' \'> ' \
    '<!ENTITY pi		\' \'> ' \
    '<!ENTITY rho		\' \'> ' \
    '<!ENTITY sigmaf	\' \'> ' \
    '<!ENTITY sigma		\' \'> ' \
    '<!ENTITY tau		\' \'> ' \
    '<!ENTITY upsilon	\' \'> ' \
    '<!ENTITY phi		\' \'> ' \
    '<!ENTITY chi		\' \'> ' \
    '<!ENTITY psi		\' \'> ' \
    '<!ENTITY omega		\' \'> ' \
    '<!ENTITY thetasym	\' \'> ' \
    '<!ENTITY upsih		\' \'> ' \
    '<!ENTITY piv		\' \'> ' \
    '<!ENTITY OElig		\' \'> ' \
    '<!ENTITY oelig		\' \'> ' \
    '<!ENTITY Scaron	\' \'> ' \
    '<!ENTITY scaron	\' \'> ' \
    '<!ENTITY Yuml		\' \'> ' \
    '<!ENTITY fnof		\' \'> ' \
    '<!ENTITY circ		\' \'> ' \
    '<!ENTITY tilde		\' \'> ' \
    '<!ENTITY ndash		\' \'> ' \
    '<!ENTITY mdash		\' \'> ' \
    '<!ENTITY lsquo		\' \'> ' \
    '<!ENTITY rsquo		\' \'> ' \
    '<!ENTITY sbquo		\' \'> ' \
    '<!ENTITY ldquo		\' \'> ' \
    '<!ENTITY rdquo		\' \'> ' \
    '<!ENTITY bdquo		\' \'> ' \
    '<!ENTITY dagger	\' \'> ' \
    '<!ENTITY Dagger	\' \'> ' \
    '<!ENTITY bull		\' \'> ' \
    '<!ENTITY hellip	\' \'> ' \
    '<!ENTITY permil	\' \'> ' \
    '<!ENTITY prime		\' \'> ' \
    '<!ENTITY Prime		\' \'> ' \
    '<!ENTITY lsaquo	\' \'> ' \
    '<!ENTITY rsaquo	\' \'> ' \
    '<!ENTITY oline		\' \'> ' \
    '<!ENTITY euro		\' \'> ' \
    '<!ENTITY trade		\' \'> ' \
    '<!ENTITY larr		\' \'> ' \
    '<!ENTITY uarr		\' \'> ' \
    '<!ENTITY rarr		\' \'> ' \
    '<!ENTITY darr		\' \'> ' \
    '<!ENTITY harr		\' \'> ' \
    '<!ENTITY crarr		\' \'> ' \
    '<!ENTITY lceil		\' \'> ' \
    '<!ENTITY rceil		\' \'> ' \
    '<!ENTITY lfloor	\' \'> ' \
    '<!ENTITY rfloor	\' \'> ' \
    '<!ENTITY loz		\' \'> ' \
    '<!ENTITY spades	\' \'> ' \
    '<!ENTITY clubs		\' \'> ' \
    '<!ENTITY hearts	\' \'> ' \
    '<!ENTITY shy   	\' \'> ' \
    '<!ENTITY cedil   	\' \'> ' \
    '<!ENTITY diams		\' \'> ' \
    ']>'
wrongStart = "<xbrl"
rightStart = "\n" + dtd + "\n<xbrl"